### ISSUE TITLE
No Checkout Agreement Field

### ISSUE THREAD

**Issue by malikabid** [payfort/magento2-payfort#15]
Dear Developer,

I just found that if i enable checkout agreement on my website. All payment methods except PayFort
show that field and this is causing problems in checkout process.

![screenshot-roadmaster lx-2019 03 12-15-39-13](https://user-images.githubusercontent.com/1906433/54192066-27efd100-44dd-11e9-925f-abec32192131.png)
![screenshot-roadmaster lx-2019 03 12-15-39-13(1)](https://user-images.githubusercontent.com/1906433/54192074-2aeac180-44dd-11e9-9c83-43ecfc573487.png)

**Comment by DeyaZ88** [comment]
Dear @malikabid thank you for contacting us,
we check this issue and solve it ASPA.

**Comment by DeyaZ88** [comment]
Dear @malikabid , I fixed this issue and pushed it to my account https://github.com/DeyaZ88/magento2-payfort

can you try it and confirm if it working, if confirmed I will proceed the merge to Payfort account.

**Comment by DeyaZ88** [comment]
the change is now pushed to master branch, please update your plugin.

**Comment by malikabid** [comment]
Updated - thank you
