### ISSUE TITLE
Payfort Payment method error

### ISSUE THREAD

**Issue by somat211** [payfort/magento2-payfort#2]
We are using payfort payment method.Currently we have configured test account details. When we placed order it is redirecting to  https://sbcheckout.payfort.com/FortAPI/validateRequest?_s=0#Again-No-back-button and returning error message "Invalid transaction source". Error code is 00040. Could you please let me know why this is happening?

**Comment by mohannadsaleh** [comment]
Thank you for contacting us , for integration issues please contact our integration team integration@payfort.com they are your best point of contact to assist with the issues during the integration with the FORT platform .

Best Regards, 
Mohannad Saleh
