### ISSUE TITLE
Transactional emails issue

### ISSUE THREAD

**Issue by moejoee91** [payfort/magento2-payfort#2]
Preconditions
ubuntu server
Magento 2 Community Edition 2.2.3
Environment : Production
Third party modules : yes

we're using postfix to rely emails to mailgun since email sending is blocked on GCP

When a customer places an order with your module enabled: 

Expected result :  
order confirmation email is sent 

actual result: 
order confirmation email is not sent 

the problem is solved when your module is disabled

**Comment by DeyaZ88** [comment]
Hello Mohamed, 

this is not an issue from our plugin , 
we only send the email when the user complete the payment, 
and this should not affect the order confirmation email.

**Comment by moejoee91** [comment]
Can you please validate the case? 
it's present on 2 different installations

**Comment by muhammadzia-se** [comment]
Hi @moejoee91 
I am also facing same issue. when your extension is disabled, it works fine sending emails fine. but after enabling it is not working.

**Comment by moejoee91** [comment]
Hello @muhammadzia-se 
Have you found a solution for this? i'm still stuck. 
Any news guys? @DeyaZ88

**Comment by moamen-ui** [comment]
I am also facing same issue.

**Comment by DeyaZ88** [comment]
Hello guys,
We will check this issue and try to solve ASAP.

**Comment by DeyaZ88** [comment]
@moejoee91 @muhammadzia-se @moamen-ui 
I submitted a pull request can you check , it should solve the issue 
https://github.com/payfort/magento2-payfort/pull/3/files

will merge to master branch once verified and tested , please update us

**Comment by moejoee91** [comment]
Thanks for the update, i can confirm it's working now

**Comment by moamen-ui** [comment]
@moejoee91 Could you please confirm if your magento didn't send email from postmaster@yourdomain.com?
Because, after latest update from @DeyaZ88 magento send email successful but the sender always postmaster not the sender configured in magento admin.
after disable the module magento send emails from the correct sender.

**Comment by moejoee91** [comment]
for our case, it's showing the correct email address specified in the back-end. 
i'm not sure what could be the issue in your setup.

**Comment by moejoee91** [comment]
@moamen-ui 
after updating to 2.2.4, we are now having the same issue as you, all emails are sent from postmaster@domainname.com

Can you guys check ? @DeyaZ88
