### ISSUE TITLE
Order Emails not being sent

### ISSUE THREAD

**Issue by malikabid** [payfort/magento2-payfort#4]
Hi,
I am using your module with Magento 2.1.9 and it is not sending order confirmation emails when I chose Credit Card payment with PayFort.
With earlier version order confirmation emails were not being sent at all. But now the issue is with only PayFort payment options.

I tried to uncomment line 527, but that did not help.

Please help me as I need it urgently.

**Comment by allinvinod** [comment]
I am having the same issue. If I disable PayFort payment method then order confirmation email is sent to customer. It PayFort payment method is enable then order confirmation email is not sent to customer and message showing in admin (The order confirmation email is not sent).

@malikabid , have you got any solution regarding this issue?

**Comment by malikabid** [comment]
Just update the extension. The developer claims to have fixed it.

If it’s not resolved, just check the observer file and chage 
setCanSendNewEmailFlag(true);

This work around will definitely work. For me this worked.

**Comment by allinvinod** [comment]
Thank you @malikabid , I have updated it. I had seen updated extension after posting query.

**Comment by muhammadzia-se** [comment]
Hi Experts,

@allinvinod 

please help me to resolve these below two issues:
1: email not sending (extension is updated)
2: not mentioning about fails of order
your earliest response will be highly appriciated.

Regards,
Zia

**Comment by malikabid** [comment]
@muhammadzia-se 
for point 1 -- see my second comment above.

**Comment by muhammadzia-se** [comment]
what is for 2 point... 
thanks

**Comment by allinvinod** [comment]
@malikabid 
there is no option to allow credit or debit card types in admin. Currently, VISA and MASTERCARD icons are showing on checkout page.

I want to add another icon for MADA. 

Can you please help me to add MADA icon on the checkout page?

I have added MADA in  app/code/Payfort/Fort/Model/Method/Cc.php

```
public function getCcAvailableTypes()
    {
        $types = $this->_paymentConfig->getCcTypes();
        $availableTypes = 'VI,MC,MADA';
        if ($availableTypes) {
            $availableTypes = explode(',', $availableTypes);
            foreach ($types as $code => $name) {
                if (!in_array($code, $availableTypes)) {
                    unset($types[$code]);
                }
            }
        }
        return $types;
    }
```
But still it is not showing. I have added icon in media.

**Comment by muhammadzia-se** [comment]
Still waiting for helpful response.

2: not mentioning about failing orders.
Regards,

**Comment by malikabid** [comment]
Dear @muhammadzia-se  
It doesn't work like this. You have to activate "Payment Methods" in payfort account and then in website configuration - then only it will work.
For further instructions contact PayFort support to get your MADA enabled.

**Comment by muhammadzia-se** [comment]
Hi @malikabid,
Thanks for your reply.
i already done this. but i am unable to understand why it is sending order emails if it is fail or close the payment page by customer. 

Regards,
Zia

**Comment by malikabid** [comment]
@muhammadzia-se 
I have the same issue. I did connect to support team just yesterday, and according to them, I am only one to report this issue. I would suggest and request you to submit a support ticket so that they might know that it is an issue and they try to solve this. Please!

**Comment by muhammadzia-se** [comment]
@malikabid,
today i contacted them. let see.

Thanks for your time.
