### ISSUE TITLE
Knockout | Unable To Process Binding

### ISSUE THREAD

**Issue by sayedMurtadha** [payfort/magento2-payfort#40]
Console Error log:
```
knockout.js:2821 Uncaught Error: Unable to process binding "if: function(){return (canInitialise()) }"
Message: Unable to process binding "if: function(){return (hasVerification()) }"
Message: Unable to parse bindings.
Bindings value: attr: {id: getCode() + '_remember_me'
Message: Unbalanced parentheses, braces, or brackets
...
```
The issue is due to a missing `}` at the end of the `data-bind`:
https://github.com/payfort/magento2-payfort/blob/e835862b27fca666b72cc1f1fb76d6c4f46bf807/magento2-aps/Amazonpaymentservices/Fort/view/frontend/web/template/payment/aps-form-merchant-page2.html#L224

And:
https://github.com/payfort/magento2-payfort/blob/e835862b27fca666b72cc1f1fb76d6c4f46bf807/magento2-aps/Amazonpaymentservices/Fort/view/frontend/web/template/payment/aps-installment.html#L221

**Comment by PayFortIntegration** [comment]
Hi Sayed, 

Thanks for reaching us!

Could you please make sure to use our latest Magento plugin from the following URL in order to solve the issue:
https://marketplace.magento.com/amazonpaymentservices-module-fort.html

Thanks
