### ISSUE TITLE
Payfort payment method not working when single payment method exist.

### ISSUE THREAD

**Issue by somat211** [payfort/magento2-payfort#5]
We have selected only one payment method (Payfort Payment method) from admin panel.It is show on checkout page but when we try to place order, we get below error.
"Property 'Title' does not have corresponding setter in class Magento\Quote\Api\Data\PaymentInterface."
Could you please help us how to resolve this issue.
Thanks in Advance.

**Comment by mohannadsaleh** [comment]
hello,

Can you please give us more details regarding mentioned issue , also please feel free always to contact our integration team integration@payfort.com for more assistance during the integration with PAYFORT 

Best Regards,
